[김경천]Add:장바구니 등록 구현중
wecode-bootcamp-korea/21-1st-seolleungbeer-backend pull request #10
Opened 2021-06-14 02:55 UTC by mono6

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-06-14 15:26 UTC, Kang-kyunghun requested changes

2021-06-14 15:26 UTC, Kang-kyunghun commented on orders/views.py
> +
공백 제거해 주세요.

2021-06-14 15:26 UTC, Kang-kyunghun commented on orders/views.py
> +            if OrderItem.objects.filter(Q(order=order) & Q(product=product)):
```suggestion
            if OrderItem.objects.filter(order=order, product=product):
```
& 조건일 때는 굳이 Q을 사용하지 않아도 됩니다.

2021-06-14 15:27 UTC, Kang-kyunghun commented
- PR 내용이 팀원들과 공유가 되지 않았나요?
- 전체적인 내용을 모델과 같이 봐야 할 것 같아서 구두 리뷰 드리겠습니다.

2021-06-15 01:27 UTC, mono6 commented on orders/views.py
> +            if OrderItem.objects.filter(Q(order=order) & Q(product=product)):
넵 수정하겠습니다!

2021-06-15 01:29 UTC, mono6 commented
> * PR 내용이 팀원들과 공유가 되지 않았나요?
> * 전체적인 내용을 모델과 같이 봐야 할 것 같아서 구두 리뷰 드리겠습니다.

체크를 깜박했습니다 . 수정했습니다!

2021-06-15 06:36 UTC, Kang-kyunghun requested changes

2021-06-15 06:36 UTC, Kang-kyunghun commented on orders/urls.py
> +
공백 하나로 해주세요.

2021-06-15 06:36 UTC, Kang-kyunghun commented on orders/views.py
> +            OrderItem.objects.update_or_create(
```suggestion
            if OrderItem.objects.filter(order=order , product_id=product).exists():
                current_amount = OrderItem.objects.get(order=order ,product_id = product).amount
                
            OrderItem.objects.update_or_create(
```

2021-06-15 10:41 UTC, mono6 commented on orders/urls.py
> +
네 제거햇습니다!

2021-06-15 10:41 UTC, mono6 commented on orders/views.py
> +            OrderItem.objects.update_or_create(
네 수정했습니다!

2021-06-16 01:15 UTC, Kang-kyunghun requested changes

2021-06-16 01:15 UTC, Kang-kyunghun commented on orders/urls.py
> +    path('/cart/<int:order_id>', CartView.as_view())
쓰이는 곳이 없는 것 같은데 확이 부탁드립니다.

2021-06-16 01:15 UTC, Kang-kyunghun commented on orders/views.py
> +            order, created = Order.objects.get_or_create(
```suggestion
            order, is_created = Order.objects.get_or_create(
```
boolean을 갖는 변수는 보통 앞에 is_을 붙여줍니다.

2021-06-16 01:15 UTC, Kang-kyunghun commented on orders/views.py
> +            orderitem, created = OrderItem.objects.update_or_create(
```suggestion
            orderitem, is_created = OrderItem.objects.update_or_create(
```
여기도 boolean을 갖기 때문에 다음과 같이 수정하면 좋을 것 같습니다.

2021-06-16 01:15 UTC, Kang-kyunghun commented on orders/views.py
> +            return JsonResponse({'message':"SUCCESS", "order_number":order.order_number, "id":orderitem.id},status=200)
장바구니 등록 후 주문번호를 넘겨주는 이유가 있나요?

2021-06-16 01:20 UTC, mono6 commented on orders/urls.py
> +    path('/cart/<int:order_id>', CartView.as_view())
수정하겠습니다!

2021-06-16 01:20 UTC, mono6 commented on orders/views.py
> +            order, created = Order.objects.get_or_create(
넵 수정하겠습니다!

2021-06-16 01:20 UTC, mono6 commented on orders/views.py
> +            orderitem, created = OrderItem.objects.update_or_create(
네 수정하겠습니다!

2021-06-16 02:23 UTC, mono6 commented on orders/views.py
> +            return JsonResponse({'message':"SUCCESS", "order_number":order.order_number, "id":orderitem.id},status=200)
결제하기 담당하는 정연님께 전해주기위해서 프론트에게 건내준후 다시 정연님한테 건내줄계획이였는데 계획변경되서 없어될거같다고합니다!

2021-06-16 06:14 UTC, Kang-kyunghun requested changes

2021-06-16 06:14 UTC, Kang-kyunghun commented on orders/views.py
> +            return JsonResponse({'message':"SUCCESS", "id":orderitem.id},status=200)
```suggestion
            return JsonResponse({'message':"SUCCESS", "order_item_id":orderitem.id},status=200)
```
어떤것의 id인지 명확히 해주는 것이 좋습니다.

2021-06-16 06:14 UTC, Kang-kyunghun commented on orders/views.py
> +            orderitem, is_created = OrderItem.objects.update_or_create(
```suggestion
            order_item, is_created = OrderItem.objects.update_or_create(
```
단어간에 _로 구분해 주세요.

2021-06-16 06:21 UTC, mono6 commented on orders/views.py
> +            return JsonResponse({'message':"SUCCESS", "id":orderitem.id},status=200)
넵 수정했습니다!

2021-06-16 06:21 UTC, mono6 commented on orders/views.py
> +            orderitem, is_created = OrderItem.objects.update_or_create(
넵 수정했습니다!

2021-06-16 06:24 UTC, Kang-kyunghun commented
LGTM~!!

2021-06-16 06:24 UTC, merged