[김경천]장바구니 수량변경
wecode-bootcamp-korea/21-1st-seolleungbeer-backend pull request #17
Opened 2021-06-16 07:05 UTC by mono6

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 장바구니 수량변경
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)
<img width="539" alt="스크린샷 2021-06-16 16 04 38" src="https://user-images.githubusercontent.com/76802269/122173254-8fff9f80-cebc-11eb-90ac-54db79a65ced.png">

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-06-16 09:42 UTC, Kang-kyunghun requested changes

2021-06-16 09:42 UTC, Kang-kyunghun commented on orders/views.py
> +            order   = Order.objects.get(user_id=user.id, order_status_id=OrderStatus.PENDING)
1. 굳이 .get으로 product 객체를 가져오지 말고, product_id가지고만 데이터를 수정해 보세요.
2. product_id만을 사용할려면 product_id의 존재 여부를 판단하는 로직도 있으면 좋겠죠?
3. order가 아닌 OrderItem의 데이터를 가져와 수량을 수정해 보세요.

2021-06-16 11:22 UTC, mono6 commented on orders/views.py
> +            order   = Order.objects.get(user_id=user.id, order_status_id=OrderStatus.PENDING)
if not Product.objects.filter(id=product).exists():
                return JsonResponse({'message':'PRODUCT_DOES_NOT_EXIST'}, status=404)

            if not OrderItem.objects.filter(order__user=user, product=product, order__order_status_id = OrderStatus.PENDING).exists():
                return JsonResponse({'message':"PRODUCT_DOES_NOT_MATCH"},status=404)

            order_item = OrderItem.objects.get(order__user=user, order__order_status_id=OrderStatus.PENDING, product_id=product)
            order_item.amount=data['amount']
            order_item.save()


이렇게 수정하였습니다!

2021-06-17 01:29 UTC, Kang-kyunghun commented
고생하셨습니다~~~!!

2021-06-17 01:31 UTC, Kang-kyunghun requested changes

2021-06-17 01:31 UTC, Kang-kyunghun commented on orders/views.py
> +                return JsonResponse({'message':"PRODUCT_DOES_NOT_MATCH"},status=404)
이거 잘 동작 하나요? 확인 한 번 해보세요.

2021-06-17 01:37 UTC, mono6 commented on orders/views.py
> +                return JsonResponse({'message':"PRODUCT_DOES_NOT_MATCH"},status=404)
확인완료했습니다!

PRODUCT_DOES_NOT_EXIST
<img width="410" alt="스크린샷 2021-06-17 10 36 43" src="https://user-images.githubusercontent.com/76802269/122317088-ea017300-cf57-11eb-86ae-e1810d769da3.png">

PRODUCT_DOES_NOT_MATCH

<img width="539" alt="스크린샷 2021-06-17 10 37 20" src="https://user-images.githubusercontent.com/76802269/122317145-01d8f700-cf58-11eb-8a8a-28b80ac9b70c.png">

2021-06-17 04:35 UTC, Kang-kyunghun commented
고생했어요~

2021-06-17 04:35 UTC, merged