[김경천]productdetail 뷰 완성
wecode-bootcamp-korea/21-1st-seolleungbeer-backend pull request #5
Opened 2021-06-10 06:56 UTC by mono6

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 상세페이지 완성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 상품상세페이지 뷰 완성
- Path parameter로 상품id를 이용하여 데이터전달
- 프론트님과 상의하여 result 리스트에서 info 딕셔너리를 생성하여 데이터나눠서전달
- 
![스크린샷 2021-06-10 15 51 56](https://user-images.githubusercontent.com/76802269/121478260-cd1eea00-ca03-11eb-9aaa-560a4c320e9b.png)
## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-06-10 08:23 UTC, Kang-kyunghun requested changes

2021-06-10 08:23 UTC, Kang-kyunghun commented on db_uploader.py
> +                                        )
제거해 주세요.

2021-06-10 08:23 UTC, Kang-kyunghun commented on products/urls.py
> +from products.views import ProductDetail
import 라인 맞춰 주세요.

2021-06-10 08:23 UTC, Kang-kyunghun commented on products/views.py
> +from .models import Product, ProductImage, ProductInfo, ImageType,SubCategory
import 라인 맞춰주세요.

2021-06-10 08:23 UTC, Kang-kyunghun commented on products/views.py
> +            product = Product.objects.get(id=product_id)
product_id 존재 유무 예외처리 추가해 주세요.

2021-06-10 09:30 UTC, mono6 commented on db_uploader.py
> +                                        )
네 제거했습니다

2021-06-10 09:30 UTC, mono6 commented on products/views.py
> +            product = Product.objects.get(id=product_id)
```
 if not Product.objects.filter(id=product_id).exists():
                return JsonResponse({'MESSAGE' : 'PRODUCT_DOES_NOT_EXIST'}, status=404)
```
추가했습니다.

2021-06-10 11:01 UTC, Kang-kyunghun requested changes

2021-06-10 11:01 UTC, Kang-kyunghun commented on products/views.py
> +                    }for image in images],
```suggestion
                    }for image in product.productimage_set.all()],
```
자주 쓰이지 않고, 가독성을 해치지 않기 때문에 따로 변수에 담지 않아도 좋을 것 같습니다.

2021-06-10 11:57 UTC, mono6 commented on products/views.py
> +                    }for image in images],
네 수정했습니다! 감사합니다

2021-06-11 01:53 UTC, Kang-kyunghun commented
LGTM~~!!

2021-06-11 01:53 UTC, merged