Add: 이메일, 전화번호 중복 검사 기능 추가
wecode-bootcamp-korea/21-1st-seolleungbeer-backend pull request #7
Opened 2021-06-11 07:37 UTC by hwangboksil

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 이메일, 전화번호 중복 검사 기능 추가
		 
## 수정 사항들 자세한 내용
- 이메일, 전화번호 중복 검사 기능 뷰 작성
: 웹 페이지에서 버튼을 눌러 이메일과 전화번호 중복하도록 기능 추가
- 웹페이지 예시
![스크린샷, 2021-06-11 16-33-54](https://user-images.githubusercontent.com/66759928/121648801-db880700-cad2-11eb-8161-855d6b7ddf23.png)

- 이메일 중복 체크 테스트
![스크린샷, 2021-06-11 16-29-33](https://user-images.githubusercontent.com/66759928/121648957-02463d80-cad3-11eb-9ae3-6216e81218c8.png)

- 전화번호 중복 체크 테스트
![스크린샷, 2021-06-11 16-29-37](https://user-images.githubusercontent.com/66759928/121648992-0d00d280-cad3-11eb-8fe1-77ef249f5cc1.png)

## 기타 질문 및 특이 사항
-

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-06-11 09:41 UTC, Kang-kyunghun requested changes

2021-06-11 09:41 UTC, Kang-kyunghun commented on users/views.py
> +                return JsonResponse({'message': 'INVALID_MOBILE'}, status=400)
여기도 존재 여부보다 형식을 먼저 확인하는 것이 더 효율적이라고 생각됩니다.

2021-06-11 09:41 UTC, Kang-kyunghun commented on users/views.py
> +
존재 여부보다 형식을 먼저 확인하는 것이 더 효율적이라고 생각됩니다. 형식이 맞지 않는다면 데이터베이스에 등록이 안 되어 있을텐데, 굳이 데이터베이스를 갔다 오기 때문입니다.

2021-06-11 10:00 UTC, hwangboksil commented on users/views.py
> +                return JsonResponse({'message': 'INVALID_MOBILE'}, status=400)
수정했습니다!

2021-06-11 10:00 UTC, hwangboksil commented on users/views.py
> +
수정했습니다!

2021-06-14 01:37 UTC, Kang-kyunghun commented
LGTM~~!!

2021-06-14 01:38 UTC, merged