Add: 상품 리스트 페이지 추가
wecode-bootcamp-korea/21-1st-seolleungbeer-backend pull request #9
Opened 2021-06-12 03:22 UTC by geekanne

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 상품 리스트 페이지 구현
		 
## 수정 사항들 자세한 내용
1. 2개 부분으로 나누어 구현
- 카테고리 리스트 요청/응답 (1번만) (프 추가예정)
- 상품 리스트 요청/응답(필터, 페이지 바뀔 때마다 새로 요청/응답)
2. 페이지네이션 구현
- 케이스별 메세지 같이 전송
- 마지막 페이지인 경우, '마지막 페이지' 메세지 / 아직 상품이 남은 경우 '상품이 남았습니다' 메세지
3. 필터링 구현
4. 예외처리 케이스별 구현
- 카테고리 데이터가 없거나 너무 많은 경우 >> (프) 상품 메인으로 리다이렉트 (프 추가 예정)
- 상품 데이터가 없는 경우 >> (프) 상품이 없는 페이지 ("해당하는 상품이 없습니다")
- 상품의 이미지가 없는 경우 >> (프) 디폴트 이미지로 대체
## 기타 질문 및 특이 사항
1. 현재 카테고리의 모든 상품을 찾아온 후 >> 그 중 현재 페이지를 찾도록 했는데,
상품이 적은 경우에는 문제가 없지만,
상품이 많은 경우에는 처음부터 현재 카테고리+현재 상품만 찾아오도록 하는 것이 더 효율적이지 않을까 싶었는데,
그러면 코드가 너무 길어져 가독성이 떨어지는 것 같아서 일단 그냥 했는데요,
보통 어떤 쪽으로 구현하나요?
2. 필터링/페이지가 바뀔 때마다 굳이 카테고리를 다시 전달할 필요가 없을 듯 해,
카테고리 전달과, 상품 리스트 전달을 각각 url을 나누어 구현했는데, 실제로 이렇게 하는 경우가 많나요?
3. 오류에 대해 리다이렉트되도록 설정하려 하는데, 혹시 투머치일까요?
- ex) 없는 카테고리를 선택하여 DoesNotExist 에러가 난 경우, (백) 에러 메세지 >> (프) 상품 메인으로 리다이렉트 되도록 함
- 상품리스트 페이지 내에서는 잘못 선택할 수 없지만, 다른 메뉴에서 잘못 되어 연결되어있거나, 구글 검색결과에 남아있거나 등등의 경우, 리다이렉션이 필요하지 않을까 싶어서 해보려합니다.
4. 이미지가 없는 경우, 디폴트 이미지가 뜨도록 하는 처리를 프런트에서 하는 것이 맞을까요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-06-14 02:50 UTC, Kang-kyunghun requested changes

2021-06-14 02:50 UTC, Kang-kyunghun commented on .vscode/settings.json
> +}
불필요한 파일 제거해 주세요.

2021-06-14 02:50 UTC, Kang-kyunghun commented on products/views.py
> +                result[category.english_name] = [sub.english_name for sub in subcategories]
```suggestion
                subcategories = SubCategory.objects.filter(category=category)
                result[category.english_name] = [sub.english_name for sub_category in  category.sub_category_set.all() ]
```

2021-06-14 02:50 UTC, Kang-kyunghun commented on products/views.py
> +            return JsonResponse({'message':'Category Does Not Exist'}, status=400)
get을 사용하지 않기 때문에 발생하지 않는 예외처리입니다.

2021-06-14 02:50 UTC, Kang-kyunghun commented on products/views.py
> +            limit         = int(request.GET.get('limit') or 6)
```suggestion
            offset        = int(request.GET.get('offset', 0)
            limit         = int(request.GET.get('limit', 6) 
```

2021-06-14 02:50 UTC, Kang-kyunghun commented on products/views.py
> +
1. 카테고리 필터링
```
category = '술'
Product.objects.filter(sub_category__category__korean_name = category)
```
2. sub_category = '맥주'
```
Product.objects.filter(sub_category__korean_name = sub_category)

2021-06-14 02:50 UTC, Kang-kyunghun commented on products/views.py
> +                    image_url = "No Image"
이미지가 없는 경우는 그냥 빈 list를 보내서 프론트에서 처리 할 수 있도록 해주세요.

2021-06-14 02:50 UTC, Kang-kyunghun commented on products/views.py
> +
image = product.productimage_set.filtert(image_type__type="1000*000")

2021-06-15 02:52 UTC, geekanne commented on .vscode/settings.json
> +}
반영했습니다!

2021-06-15 02:53 UTC, geekanne commented on products/views.py
> +                result[category.english_name] = [sub.english_name for sub in subcategories]
수정완료했습니다!

2021-06-15 02:53 UTC, geekanne commented on products/views.py
> +            return JsonResponse({'message':'Category Does Not Exist'}, status=400)
수정완료했습니다!

2021-06-15 02:53 UTC, geekanne commented on products/views.py
> +            limit         = int(request.GET.get('limit') or 6)
수정완료했습니다!

2021-06-15 02:53 UTC, geekanne commented on products/views.py
> +
수정완료했습니다!

2021-06-15 02:53 UTC, geekanne commented on products/views.py
> +                    image_url = "No Image"
수정완료했습니다!

2021-06-15 02:53 UTC, geekanne commented on products/views.py
> +
수정완료했습니다!

2021-06-15 02:55 UTC, geekanne commented
수정완료했습니다!
1. object를 가져오는게 아닌, 역참조로 모두 가져올 수 있도록 변경
2. Q 객체와 필터를 사용하여 필터링/페이징을 모두 끝낸 후, 마지막에 한 번만 DB를 가져올 수 있도록 변경
3. 값이 없는 경우 빈 배열을 반환하여 프런트에서 처리할 수 있도록 변경

2021-06-15 03:35 UTC, Kang-kyunghun requested changes

2021-06-15 03:35 UTC, Kang-kyunghun commented on products/views.py
> +            q = Q()
```suggestion
        q = Q()
        if subcategories:
            q &= Q(sub_category__english_name=subcategories)
            
        if category:
            q &= Q(sub_category__category__english_name=category)
      
```
- print 제거해 주세요.
- 위와 같이 수정하면 좋을 것 같습니다.

2021-06-15 03:35 UTC, Kang-kyunghun commented on products/views.py
> +        message          = int(products.count() <= (offset+limit))
```suggestion
        is_last_page          = int(products.count() <= (offset+limit))
```
- 메시지로 보내지 말고 result 안에 추가해 주세요.

2021-06-15 03:35 UTC, Kang-kyunghun commented on products/views.py
> +            }
list comprehension으로 바꿔보세요~

2021-06-15 05:23 UTC, geekanne commented on products/views.py
> +            q = Q()
수정 완료했습니다!

2021-06-15 05:23 UTC, geekanne commented on products/views.py
> +        message          = int(products.count() <= (offset+limit))
수정 완료했습니다!

2021-06-15 05:23 UTC, geekanne commented on products/views.py
> +            }
수정 완료했습니다!

2021-06-15 06:45 UTC, Kang-kyunghun requested changes

2021-06-15 06:45 UTC, Kang-kyunghun commented on products/views.py
> +        if subcategories:
```suggestion
        subcategories = request.GET.get('subcategory')

        q = Q()
        
        if subcategories:
```

2021-06-15 06:45 UTC, Kang-kyunghun commented on products/views.py
> +            for product in products_in_page]
```suggestion
            } for product in products_in_page]
```

2021-06-16 06:19 UTC, geekanne commented on products/views.py
> +        if subcategories:
수정 완료했습니다!

2021-06-16 06:20 UTC, geekanne commented on products/views.py
> +            for product in products_in_page]
수정 완료했습니다!

2021-06-16 07:31 UTC, Kang-kyunghun commented
LGTM~~!!!

2021-06-16 07:31 UTC, merged